name: install dependencies

inputs:
  python_version:
    required: true
    default: 3.12

outputs:
  output_var:
    description: 'An output that is computed in the action'
    value: ${{ steps.set_output_var.outputs.output_var }}

runs:
  using: "composite"
  steps:

    - name: Checlout repo 
      uses: actions/checkout@v4.2.2
    
    - name: astral-sh/setup-uv
      id: setup-uv
      uses: astral-sh/setup-uv@v4.2.0
      with:
        python-version: ${{ inputs.python_version }}     
        enable-cache: true
        cache-dependency-glob: |
          **/requirements*.txt
          **/uv.lock
          **/pyproject.toml

    - name: Install Python ${{ inputs.python_version }}
      shell: bash
      run: uv python install ${{ inputs.python_version }}

    - name: Create VENV
      shell: bash
      run: uv venv

    - name: Install requirements
      shell: bash
      working-directory: src/
      run: |
        . ../.venv/bin/activate
        uv pip install -r pyproject.toml
      
    - name: run python script
      shell: bash
      run: |
        . .venv/bin/activate
        python3 src/main.py

    - name: Checking cache restore
      shell: bash
      if: steps.setup-uv.outputs.cache-hit == 'true'
      run: echo "Cache was restored"

    - name: Set output variable
      shell: bash
      id: set_output_var
      run: |
        output="Cache restored"
        echo "Test: $output"
        echo "output_var=$output" >> $GITHUB_OUTPUT
              
