name: "Docker action"
description: 'Greets someone and returns always 42.'
inputs:
  input_one:  # id of input
    description: 'Input parameter one'
    required: true
    default: 'Default_Param_1'
  input_two: 
    description: 'Input parameter two'
    required: true
    default: 'Default_Param_2'
outputs:
  answer: # id of output
    description: 'The answer to everything (always 42)'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.input_one }}
    - ${{ inputs.input_two }}