name: bump lib versions

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: read

jobs:
  dependabot:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GH_TOKEN }}"

      - name: Approve dependabot PR
        run: gh pr review --approve "$PR_URL"
 
      - name: Merge dependabot PR
        run: gh pr merge --auto --merge "$PR_URL"
