name: COMPOSITE

on: workflow_dispatch

jobs:
  
  setup:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3.6.0
    
      - name: Setup
        id: composite_step
        uses: ./.github/actions/install_deps
        with:
          python_version: 3.13.1

      - name: run python script
        working-directory: src/
        run: |
          uv run main.py

      - name: Echo output from composite step
        run: echo ${{ steps.composite_step.outputs.output_var }}
